### ISSUE TITLE
Getting blobbers details from js-sdk instead of tweaking on React Sagas.

### ISSUE THREAD

**Issue by chauchausoup** [0chain/js-client-sdk#29]
I did updated the sdk as https://github.com/0chain/js-client-sdk/pull/28 but I do have a question here.
How can I use the updated SDK in explorer ? In what way I can point the updated SDK to local and nine.devnet ? 
Since sdk is coming from `"@zerochain/0chain": "^1.3.53",`  in explorer app, how to point to latest merge? or it does happen automatically ?

**Comment by haule24hdev** [comment]
@chauchausoup Publish new version for js sdk

**Comment by chauchausoup** [comment]
Whish is done by updating version field of package.json ? 
Here:
`{  "name": "@zerochain/0chain",  "version": "1.3.55",  "description": "js client library to interact with 0chain Blockchain",  "main": "index.js",  "scripts": {    "test": "echo \"Error: no test specified\" &amp;&amp; exit 1"  },`

**Comment by haule24hdev** [comment]
https://www.npmjs.com/package/@zerochain/0chain
You have to change version, it is 1.3.56
