### ISSUE TITLE
Propose changes for jssdk 1.3.70.

### ISSUE THREAD

**Issue by chauchausoup** [0chain/js-client-sdk#65]
So from now lets first propose changes to be done in the previous jssdk or things to be added on the newer version via this section at the issues and work on the list one by one. We can make multiple PRs this way and once the list items are all cleared last commit will the `npm update` followed by the `git push` of the newer version.

**1.3.70 will cover the following changes :**

- [x] GMT timestamp called from api instead of local machine.
- [x] add signature filed in file/meta endpoints
- [x] add signature fields in missing getShareInfo and postMethodTo0box 
- [x] missing private_key promoting faulty /commitMetaTxn requests
- [x] merge dependabot PRs

**Comment by chauchausoup** [comment]
https://github.com/0chain/js-client-sdk/pull/64 for GMT timestamp called from api instead of local machine.

**Comment by chauchausoup** [comment]
https://github.com/0chain/js-client-sdk/pull/66 for:

-  add signature filed in file/meta endpoints
-  add signature fields in missing getShareInfo and postMethodTo0box

**Comment by shaktals** [comment]
I suggest we add to this the merging of dependabot automatic PRs to fix dependency vulnerabilities.

**Comment by chauchausoup** [comment]
> I suggest we add to this the merging of dependabot automatic PRs to fix dependency vulnerabilities.

Yes @shaktals please add the respective task on the checkbox.

**Comment by chauchausoup** [comment]
_**GMT timestamp called from api instead of local machine.**_ needs time so not including in the update.
