### ISSUE TITLE
Re check 0box endpoints.

### ISSUE THREAD

**Issue by chauchausoup** [0chain/js-client-sdk#67]
**/shareinfo** which is being used in [jssdk](https://github.com/0chain/js-client-sdk/blob/ff1c43a00d5b45f0c976d55cc88b390653c23b47/index.js#L104) is not found in the [0box docs](https://github.com/0chain/0box#readme).
Even if we find this endpoint under operation, it is not including all the Required headers in the axios requests. Also most of the 0box endpoints are not following the guidelines as per the docs. We need to do a full round of investigation on 0box requests.

**Comment by chauchausoup** [comment]
We do have three separate GET, POST and DELETE methods to invoke shared files via 0box but it seems that we are relying on localStorage for performing this task.

**Comment by chauchausoup** [comment]
It seems that we are leveraging such backend based shared item in 0box mode only. Since 0box mode requires token and differs somewhat from 0proxy, will halt the revision of getShareInfo, postShareInfo and deleteShareObject methods for now.

**Comment by shaktals** [comment]
About the /shareinfo we have this update on slack:

Artem B  16 hours ago
@Anish Gupta could you pls redeploy 0box I fixed issue

**Comment by anish** [comment]
You tagged the wrong person here

**Comment by shaktals** [comment]
> You tagged the wrong person here

My bad.

**Comment by shaktals** [comment]
Stale issue, closing
