### ISSUE TITLE
Fatal crash on explorer when reloading at /0box/files

### ISSUE THREAD

**Issue by shaktals** [0chain/js-client-sdk#81]
The error report points to wasm.js line 84:

![Selection_276](https://user-images.githubusercontent.com/24679343/146262245-6261cd70-e755-4a4d-83af-284f9800adcd.png)

**Comment by shaktals** [comment]
I added the guard below on wasm.js setWallet and found out that an undefined sk (secret key) is the culprit:

![Selection_277](https://user-images.githubusercontent.com/24679343/146263892-c9e2a2a4-468d-49c2-a7b3-aff0fed4602d.png)

**Comment by chauchausoup** [comment]
@shaktals it seems that at the moment the issue is resolved. I am not able to replicate it on my end. Whats your status?

**Comment by shaktals** [comment]
Yes, it was solved by @cnlangzi on explorer side. But it's still a frailty on js-client-sdk side. I'll make a PR for it now.
